### PR TITLE
Use plugins relative to current directory

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/GoogleCloudPlatform/terraformer/issues/79

### CODE REVIEW

**Comment by sergeylanzman** [comment]
@gliptak  
Good job, I try test this on mac/linux today, 
If it's tested on windows?
Can you add to README install for windows and new options for installation for mac/linux

**Comment by gliptak** [comment]
This worked with current directory install under Windows.

Do you have a preference for one install option over the other (to help update README accordingly)?

**Comment by sergeylanzman** [comment]
I think `terraform init` more simple options. We can write first `terraform init` option and second old method

**Comment by gliptak** [comment]
@sergeylanzman please review updated README

**Comment by ankitkotnala** [comment]
Hi,
I am trying to use it on Windows but terraformer can't get the provider for Azure for some reasons 
I've done terraform init and also placed the provider files manually under 
$HOME\.terraform.d\plugins

Is there something else I need to do for it to work, the instructions on readme are not clear for windows.

**Pull request merged**
