### PR TITLE
Add cloudwatch log group terraforming

### PR DESCRIPTION
**Pull request by nimrodkor**
Adding @mikeurbanski1 's contribution to the main fork as well

### CODE REVIEW

**Comment by mikeurbanski1** [comment]
@googlebot  I fixed it.

**Comment by mikeurbanski1** [comment]
@googlebot I consent.

**Comment by mikeurbanski1** [comment]
@googlebot I consent.

**Comment by nimrodkor** [comment]
@googlebot I fixed it

**Comment by nimrodkor** [comment]
@googlebot I consent

**Pull request merged**
