### PR TITLE
Snowflake Provider

### PR DESCRIPTION
**Pull request by alldoami**
Using [terraform-provider-snowflake](https://github.com/chanzuckerberg/terraform-provider-snowflake) to import the following resources:
- database_grant
- database
- role_grant
- role
- schema_grant
- schema
- user
- view
- warehouse_grant
- warehouse

### CODE REVIEW

**Comment by sergeylanzman** [comment]
Wow,
Thanks for you PR,
2 issue before code review.
1. Can you rebase all commits to 1 or 2 commits?
2. Can you to resolve conflicts?

**Comment by shahargl** [comment]
hey @alldoami,

why did you close it? is there any way I can use snowflake provider apart from cloning the fork and building from source?

**Comment by bencohen2** [comment]
@sergeylanzman Can this be merged in?

**Comment by sergeylanzman** [comment]
@bencohen2 https://github.com/GoogleCloudPlatform/terraformer/pull/1341 can you test?

**Comment by bencohen2** [comment]
@sergeylanzman Do you have any repo-specific instructions on testing? I checked out `CONTRIBUTING.md` but didn't see anything about testing.

**Pull request closed without merging**
