### PR TITLE
fix nil port error with FromPort and ToPort for aws provider sg

### PR DESCRIPTION
**Pull request by Elliott-weeks**
This PR fixes the nil port error with FromPort and ToPort for aws provider sg

### CODE REVIEW

**Comment by Elliott-weeks** [comment]
As this is my first time contributing to the repo, @sergeylanzman can you take a look at the workflow approval, please?

**Comment by Elliott-weeks** [comment]
@sergeylanzman Would you be able to review and merge?

I believe this issue can then be closed too if all is well - https://github.com/GoogleCloudPlatform/terraformer/issues/1479

 Cheers :)

**Comment by rebjan** [comment]
@Elliott-weeks is this PR approved? or still pending?

**Comment by Elliott-weeks** [comment]
I believe it is still pending review. Would you be able to assist? @rebjan

**Comment by sayefiqb** [comment]
Has this PR been merged? I am facing issues while running the following 
`terraformer import aws --resources=sg --regions=us-east-2`

**Comment by williamrct** [comment]
Is this available yet? if not are there manual build instruction I can follow? Thank you

**Comment by williamrct** [comment]
all set thank you @sergeylanzman

**Pull request merged**
