### PR TITLE
added support to Azure app service

### PR DESCRIPTION
**Pull request by rotemavni**

### CODE REVIEW

**Comment by juno-yu** [comment]
Oh I tried something similar but wip recently too.
Some resources in azure have `ListComplete`/`ListAll` methods which also consider paging, e.g. this one has ListComplete
e.g. 
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2019-08-01/web/webapi/interfaces.go#L431

(A WIP prototype https://github.com/GoogleCloudPlatform/terraformer/compare/master...juno-yu:j-0007-add-function-app-partial?expand=1#diff-5f8bd3346315541ce78e72371e46bb71R120  I haven't finished this yet)

**Comment by rotemavni** [comment]
@googlebot I signed it!

**Comment by sergeylanzman** [comment]
Thanks! Can you add new resource to README?

**Comment by rotemavni** [comment]
> Oh I tried something similar recently too.
> Some resources in azure have `ListComplete`/`ListAll` methods which also consider paging, e.g. this one has ListComplete
> e.g.
> https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2019-08-01/web/webapi/interfaces.go#L431
> 
> (A WIP prototype https://github.com/GoogleCloudPlatform/terraformer/compare/master...juno-yu:j-0007-add-function-app-partial?expand=1#diff-5f8bd3346315541ce78e72371e46bb71R120 I haven't finished this yet)


@juno-yu 
It's a really good comment, thank you! I updated my code accordingly.

**Comment by rotemavni** [comment]
> Thanks! Can you add new resource to README?

@sergeylanzman 
Sure, README is now updated.

**Pull request merged**
