### PR TITLE
 Fixed Offset not increasing when fetching Pagerduty API

### PR DESCRIPTION
**Pull request by v0lumehi**
This pull request also fixes pagerduty_service_event_rule resources not being created properly

### CODE REVIEW

**Comment by v0lumehi** [comment]
@googlebot I signed it!

**Comment by v0lumehi** [comment]
@googlebot I fixed it.

**Comment by v0lumehi** [comment]
Seems like my formatting is broken

**Comment by v0lumehi** [comment]
> Seems like my formatting is broken

Fixed it

**Review by sergeylanzman — APPROVED** [review]

**Comment by v0lumehi** [comment]
@sergeylanzman can you review my latest changes?

**Pull request merged**
