### PR TITLE
fix(rabbitmq): fix rabbitmq problems in policies and bindings #1660

### PR DESCRIPTION
**Pull request by jotasixto**
Changes needed to solve the problem indicated in the issue #1660.

These changes solve the problems indicated in the issue. 
As we can see in the following execution:
```
❯ terraformer import rabbitmq --resources=bindings,exchanges,permissions,policies,queues,users,vhosts
2023/03/07 13:46:35 rabbitmq importing... bindings
2023/03/07 13:46:36 rabbitmq done importing bindings
2023/03/07 13:46:36 rabbitmq importing... exchanges
2023/03/07 13:46:37 rabbitmq done importing exchanges
2023/03/07 13:46:37 rabbitmq importing... permissions
2023/03/07 13:46:37 rabbitmq done importing permissions
2023/03/07 13:46:37 rabbitmq importing... policies
2023/03/07 13:46:37 rabbitmq done importing policies
2023/03/07 13:46:37 rabbitmq importing... queues
2023/03/07 13:46:38 rabbitmq done importing queues
2023/03/07 13:46:38 rabbitmq importing... users
2023/03/07 13:46:38 rabbitmq done importing users
2023/03/07 13:46:38 rabbitmq importing... vhosts
2023/03/07 13:46:39 rabbitmq done importing vhosts
2023/03/07 13:46:39 Number of resources for service bindings: 612
2023/03/07 13:46:39 Number of resources for service exchanges: 176
2023/03/07 13:46:39 Number of resources for service permissions: 90
2023/03/07 13:46:39 Number of resources for service policies: 16
2023/03/07 13:46:39 Number of resources for service queues: 262
2023/03/07 13:46:39 Number of resources for service users: 19
2023/03/07 13:46:39 Number of resources for service vhosts: 14
...
2023/03/07 13:47:26 Filtered number of resources for service exchanges: 176
2023/03/07 13:47:26 Filtered number of resources for service permissions: 90
2023/03/07 13:47:26 Filtered number of resources for service policies: 16
2023/03/07 13:47:26 Filtered number of resources for service queues: 262
2023/03/07 13:47:26 Filtered number of resources for service users: 19
2023/03/07 13:47:26 Filtered number of resources for service vhosts: 14
2023/03/07 13:47:26 Filtered number of resources for service bindings: 612
2023/03/07 13:47:26 rabbitmq Connecting.... 
2023/03/07 13:47:26 rabbitmq save queues
2023/03/07 13:47:26 rabbitmq save tfstate for queues
2023/03/07 13:47:26 rabbitmq save users
2023/03/07 13:47:26 rabbitmq save tfstate for users
2023/03/07 13:47:26 rabbitmq save vhosts
2023/03/07 13:47:26 rabbitmq save tfstate for vhosts
2023/03/07 13:47:26 rabbitmq save bindings
2023/03/07 13:47:27 rabbitmq save tfstate for bindings
2023/03/07 13:47:27 rabbitmq save exchanges
2023/03/07 13:47:27 rabbitmq save tfstate for exchanges
2023/03/07 13:47:27 rabbitmq save permissions
2023/03/07 13:47:27 rabbitmq save tfstate for permissions
2023/03/07 13:47:27 rabbitmq save policies
2023/03/07 13:47:27 rabbitmq save tfstate for policies
❯ echo $?
0
```

### CODE REVIEW

**Comment by jotasixto** [comment]
@sergeylanzman ready to review.
Thank you in advance!

**Review by sergeylanzman — APPROVED** [review]

**Comment by jotasixto** [comment]
@sergeylanzman  Thank you very much for the approval but it seems that the validation pipelines still need to be launched. Presumably it was not done with the button `Approve and run`(https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks).

**Comment by jotasixto** [comment]
@sergeylanzman Sorry to ask again, any additional problems I should check for?

**Comment by jotasixto** [comment]
Reviewing a RabbitMQ with many bindings associated with exchanges, it was detected that the import of bindings arguments was not consistent. This 875bf6c943faa0ffbfe6e5e2c002729870477663 fixes this problem.
@sergeylanzman My apologies for requesting review and approval again :pray: . Thank you very much!

**Comment by jotasixto** [comment]
@sergeylanzman Sorry for being a pain, could you please review this PR? Thank you so much!

**Pull request merged**
