### PR TITLE
update terraform to v0.12.16

### LINKED ISSUE #286: Update terraform to v0.12.16

### PR DESCRIPTION
**Pull request by karuppiah7890**
Fix #286

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Will update PR for terraform v0.12.16

**Comment by karuppiah7890** [comment]
Pushed the changes!

**Comment by sergeylanzman** [comment]
done https://github.com/GoogleCloudPlatform/terraformer/pull/330

**Comment by karuppiah7890** [comment]
@sergeylanzman any reason why this PR wasn't considered? Is it because this one has older version and #330 has 0.12.18 ? I actually spent quite sometime on this one, probably a review comment could have been given to update. In any case, this seems to me like PRs are not exactly welcomed 😅

**Comment by karuppiah7890** [comment]
Okay, I guess I will not do vendor update PRs alone next time then 😅

**Pull request closed without merging**
