### PR TITLE
Add OctopusDeploy provider

### PR DESCRIPTION
**Pull request by rgreinho**
Adds a new provider for OctopusDeploy (https://octopus.com/).

The command imports the `tag set` resources.

### CODE REVIEW

**Comment by rgreinho** [comment]
This provider is not ready yet, but it is my first one and I thought I could ask for some help or pointers in order to complete it.

The base line seems to work, but I may have missed something somewhere as `terraformer` cannot complete the import operation due to the 2 following errors:

```
ERROR: Read resource response is null for resource octopusdeploy_tag_set.tfer--Production
ERROR: Unable to refresh resource tfer--Production
```

Here is the full output:

```
$ ./terraformer import octopusdeploy -v -r tagsets
2020/02/20 16:57:43 octopusdeploy importing... tagsets
2020-02-20T16:57:43.386-0600 [INFO]  plugin: configuring client automatic mTLS
2020-02-20T16:57:43.413-0600 [DEBUG] plugin: starting plugin: path=.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0 args=[.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0]
2020-02-20T16:57:43.415-0600 [DEBUG] plugin: plugin started: path=.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0 pid=84038
2020-02-20T16:57:43.415-0600 [DEBUG] plugin: waiting for RPC address: path=.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0
2020-02-20T16:57:43.430-0600 [INFO]  plugin.terraform-provider-octopusdeploy_v0.5.0: configuring server automatic mTLS: timestamp=2020-02-20T16:57:43.429-0600
2020-02-20T16:57:43.455-0600 [DEBUG] plugin: using plugin: version=5
2020-02-20T16:57:43.455-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.5.0: plugin address: address=/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/plugin746854845 network=unix timestamp=2020-02-20T16:57:43.455-0600
2020/02/20 16:57:43 plugin error 1: attribute "address" is required
2020-02-20T16:57:43.509-0600 [INFO]  plugin: configuring client automatic mTLS
2020-02-20T16:57:43.534-0600 [DEBUG] plugin: starting plugin: path=.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0 args=[.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0]
2020-02-20T16:57:43.537-0600 [DEBUG] plugin: plugin started: path=.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0 pid=84039
2020-02-20T16:57:43.537-0600 [DEBUG] plugin: waiting for RPC address: path=.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0
2020-02-20T16:57:43.552-0600 [INFO]  plugin.terraform-provider-octopusdeploy_v0.5.0: configuring server automatic mTLS: timestamp=2020-02-20T16:57:43.551-0600
2020-02-20T16:57:43.577-0600 [DEBUG] plugin: using plugin: version=5
2020-02-20T16:57:43.577-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.5.0: plugin address: address=/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/plugin924620914 network=unix timestamp=2020-02-20T16:57:43.577-0600
2020-02-20T16:57:43.634-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.5.0: 2020/02/20 16:57:43 [INFO] Initializing Octopus Deploy client
2020-02-20T16:57:43.634-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.5.0: 2020/02/20 16:57:43 [INFO] Octopus Deploy Client configured against default space
2020/02/20 16:57:43 Refreshing state... octopusdeploy_tag_set.tfer--Production
2020/02/20 16:57:43 ERROR: Read resource response is null for resource octopusdeploy_tag_set.tfer--Production
2020/02/20 16:57:43 ERROR: Unable to refresh resource tfer--Production
2020-02-20T16:57:43.638-0600 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/darwin_amd64/terraform-provider-octopusdeploy_v0.5.0 pid=84039
2020-02-20T16:57:43.638-0600 [DEBUG] plugin: plugin exited
2020/02/20 16:57:43 octopusdeploy Connecting....
2020/02/20 16:57:43 octopusdeploy save tagsets
2020/02/20 16:57:43 octopusdeploy save tfstate for tagsets
```

In case that helps, here is a screenshot of the Octopus test instance I am using:

image

The provider that I am using is [terraform-provider-octopusdeploy](https://github.com/OctopusDeploy/terraform-provider-octopusdeploy). And the SDK is [go-octopusdeploy](https://github.com/OctopusDeploy/go-octopusdeploy).

I am not sure why the resources cannot be refreshed, but I hope that this error is somehow common when developing new providers and that more experience contributors to this project could provide me with some guidance. 🙏

**Comment by rgreinho** [comment]
I figured it out, `GetConfig()` is the function handling passing the authentication information to Terraform! 💡 

Now the provider is ready ✅ Once it gets merged I'll work on adding more resources to import.

**Comment by sergeylanzman** [comment]
Hey @rgreinho. 
Thank for your contribution.
If you planned add more resources for this provider? Because I don't want merge provider with only one resource.

**Comment by rgreinho** [comment]
Yes I do! But I did not want to all them all before being sure my initial contribution was merged.

The Terraform provider currently supports 14 resources (out of 74 total), and I plan to add them in a very short term.

The other resources will come later as they require to update the go-sdk and the provider beforehand.

Maybe you can do a pre-review of this PR? Then I'll add 13 other resources. It each resources will follow the exact same pattern, so it should be quick and easy.

**Comment by rgreinho** [comment]
Thanks for approving @sergeylanzman! If you can merge it, I have another PR ready with the extra resources.

**Comment by rgreinho** [comment]
@sergeylanzman Would you prefer to have my second PR with the extras resources injected in this one? 

The original idea was that 2 small PRs are easier for review, but it's up to you.

**Comment by sergeylanzman** [comment]
Push all  in one PR.
Ping me when it's ready

**Comment by rgreinho** [comment]
Alright @sergeylanzman here is the full PR!

As the resources always use the same pattern, I created only one "generic" file for all of them. This leads to less copy/paste than having one resource per file, especially knowing that the provider would eventually have 74 resources.

I also added instructions to test this provider. I am not sure how I could integrate it with your  CI workflow, but if you have some pointers or suggestions I would be happy to do the work.

Last, the output reports a problem, `plugin error 1: attribute "address" is required`, as you could see bellow, but in spite of this error, the resources are created correctly:

```bash
terraformer import octopusdeploy --server "http://localhost:8081" --apikey "API-YVLL2ML1XRIBUU8GKJKEMXKPWQ" -r accounts,environments,feeds,libraryvariablesets,lifecycles,projects,projectgroups,projecttriggers,tagsets
2020/02/26 13:45:03 octopusdeploy importing... accounts
2020/02/26 13:45:03 plugin error 1: attribute "address" is required
2020/02/26 13:45:03 Refreshing state... octopusdeploy_account.tfer--Test
2020/02/26 13:45:03 octopusdeploy importing... environments
2020/02/26 13:45:03 plugin error 1: attribute "address" is required
2020/02/26 13:45:03 Refreshing state... octopusdeploy_environment.tfer--Stage
2020/02/26 13:45:03 Refreshing state... octopusdeploy_environment.tfer--Production
2020/02/26 13:45:03 Refreshing state... octopusdeploy_environment.tfer--Testing
2020/02/26 13:45:03 octopusdeploy importing... feeds
2020/02/26 13:45:03 plugin error 1: attribute "address" is required
2020/02/26 13:45:04 Refreshing state... octopusdeploy_feed.tfer--Octopus-0020-Server-0020--0028-built-002D-in-0029-
2020/02/26 13:45:04 Refreshing state... octopusdeploy_feed.tfer--feedme
2020/02/26 13:45:04 Refreshing state... octopusdeploy_feed.tfer--Octopus-0020-Server-0020-Releases-0020--0028-built-002D-in-0029-
2020/02/26 13:45:04 octopusdeploy importing... libraryvariablesets
2020/02/26 13:45:04 plugin error 1: attribute "address" is required
2020/02/26 13:45:04 Refreshing state... octopusdeploy_library_variable_set.tfer--Account-0020-IDs
2020/02/26 13:45:04 octopusdeploy importing... lifecycles
2020/02/26 13:45:04 plugin error 1: attribute "apikey" is required
2020/02/26 13:45:04 Refreshing state... octopusdeploy_lifecycle.tfer--Stage-002D-Production
2020/02/26 13:45:04 Refreshing state... octopusdeploy_lifecycle.tfer--Default-0020-Lifecycle
2020/02/26 13:45:04 octopusdeploy importing... projects
2020/02/26 13:45:04 plugin error 1: attribute "address" is required
2020/02/26 13:45:04 Refreshing state... octopusdeploy_project.tfer--Deploymark-0020-API
2020/02/26 13:45:04 octopusdeploy importing... projectgroups
2020/02/26 13:45:05 plugin error 1: attribute "address" is required
2020/02/26 13:45:05 Refreshing state... octopusdeploy_project_group.tfer--Utilities
2020/02/26 13:45:05 Refreshing state... octopusdeploy_project_group.tfer--Default-0020-Project-0020-Group
2020/02/26 13:45:05 octopusdeploy importing... projecttriggers
2020/02/26 13:45:05 plugin error 1: attribute "address" is required
2020/02/26 13:45:05 octopusdeploy importing... tagsets
2020/02/26 13:45:05 plugin error 1: attribute "address" is required
2020/02/26 13:45:05 Refreshing state... octopusdeploy_tag_set.tfer--Production
2020/02/26 13:45:05 Refreshing state... octopusdeploy_tag_set.tfer--DevOps
2020/02/26 13:45:05 octopusdeploy Connecting....
2020/02/26 13:45:05 octopusdeploy save
2020/02/26 13:45:05 octopusdeploy save tfstate
```

**Comment by sergeylanzman** [comment]
`attribute "address" is required` - it's common case where provider need not only ID, you can pass to provider address look example here https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/instances_gen.go#L46-L52

**Comment by rgreinho** [comment]
@sergeylanzman I actually fixed it by implementing the `GetBasicConfig()` function in the provider.

Now it works as expected:

```bash
terraformer import octopusdeploy --server "http://localhost:8081" --apikey "API-YVLL2ML1XRIBUU8GKJKEMXKPWQ" -r accounts,environments,feeds,libraryvariablesets,lifecycles,projects,projectgroups,projecttriggers,tagsets
2020/02/28 10:39:27 octopusdeploy importing... accounts
2020/02/28 10:39:27 Refreshing state... octopusdeploy_account.tfer--Test
2020/02/28 10:39:27 octopusdeploy importing... environments
2020/02/28 10:39:28 Refreshing state... octopusdeploy_environment.tfer--Testing
2020/02/28 10:39:28 Refreshing state... octopusdeploy_environment.tfer--Production
2020/02/28 10:39:28 Refreshing state... octopusdeploy_environment.tfer--Stage
2020/02/28 10:39:28 octopusdeploy importing... feeds
2020/02/28 10:39:28 Refreshing state... octopusdeploy_feed.tfer--Octopus-0020-Server-0020--0028-built-002D-in-0029-
2020/02/28 10:39:28 Refreshing state... octopusdeploy_feed.tfer--feedme
2020/02/28 10:39:28 Refreshing state... octopusdeploy_feed.tfer--Octopus-0020-Server-0020-Releases-0020--0028-built-002D-in-0029-
2020/02/28 10:39:28 octopusdeploy importing... libraryvariablesets
2020/02/28 10:39:28 Refreshing state... octopusdeploy_library_variable_set.tfer--Account-0020-IDs
2020/02/28 10:39:28 octopusdeploy importing... lifecycles
2020/02/28 10:39:29 Refreshing state... octopusdeploy_lifecycle.tfer--Default-0020-Lifecycle
2020/02/28 10:39:29 Refreshing state... octopusdeploy_lifecycle.tfer--Stage-002D-Production
2020/02/28 10:39:29 octopusdeploy importing... projects
2020/02/28 10:39:29 Refreshing state... octopusdeploy_project.tfer--Deploymark-0020-API
2020/02/28 10:39:29 octopusdeploy importing... projectgroups
2020/02/28 10:39:29 Refreshing state... octopusdeploy_project_group.tfer--Utilities
2020/02/28 10:39:29 Refreshing state... octopusdeploy_project_group.tfer--Default-0020-Project-0020-Group
2020/02/28 10:39:29 octopusdeploy importing... projecttriggers
2020/02/28 10:39:29 octopusdeploy importing... tagsets
2020/02/28 10:39:30 Refreshing state... octopusdeploy_tag_set.tfer--Production
2020/02/28 10:39:30 Refreshing state... octopusdeploy_tag_set.tfer--DevOps
2020/02/28 10:39:30 octopusdeploy Connecting....
2020/02/28 10:39:30 octopusdeploy save
2020/02/28 10:39:30 octopusdeploy save tfstate
```

**Pull request merged**
