### PR TITLE
Add Grafana provider

### PR DESCRIPTION
**Pull request by naag**
This PR adds a provider for Grafana that is able to collect dashboards and folders from the Grafana API. This API is supported both by Grafana Cloud and by Grafana open source.

### CODE REVIEW

**Comment by naag** [comment]
@googlebot I signed it!

**Comment by markhowardform3** [comment]
@googlebot I fixed it.

**Comment by markhowardform3** [comment]
@googlebot I consent.

**Comment by sergeylanzman** [comment]
Thanks! 
can fix the last lint error?

**Pull request merged**
