### PR TITLE
Fix azure provider by upgrading dependencies

### PR DESCRIPTION
**Pull request by pguan-ntap**
Fixes https://github.com/GoogleCloudPlatform/terraformer/issues/1149 and https://github.com/GoogleCloudPlatform/terraformer/issues/654 by upgrading various dependencies

### CODE REVIEW

**Comment by juarezr** [comment]
@pguan-ntap,

- Nice fix.
- Any chance of signing the CLA for proceeding with this PR?

**Comment by pguan-ntap** [comment]
> @pguan-ntap,
> 
>     * Nice fix.
> 
>     * Any chance of signing the CLA for proceeding with this PR?

Going through legal approval at any company, is slow, but its almost done!

**Comment by jholm117** [comment]
@pguan-ntap any luck?

**Comment by juarezr** [comment]
- PR #1369 fix this issue also.
- However, it defaults to MSAIL to authentication as ADAL is deprecated.

**Comment by sergeylanzman** [comment]
@pguan-ntap  can you to sign a Contributor License Agreement (CLA)?

**Comment by pguan-ntap** [comment]
I signed the CLA but the recheck shows code 400

**Pull request closed without merging**
